### PR TITLE
Use FQCNs for ansible.* namespaces

### PR DESCRIPTION
**Pull request by nre-ableton**
- Use FQCNs for tasks in ansible.windows namespace
- Use FQCNs for tasks in ansible.builtin namespace

### CODE REVIEW

**Comment by ala-ableton** [comment]
@nre-ableton this repository doesn't have any `requirements.yml`, though it depends on `ansible.windows`.

**Review by rco-ableton — CHANGES_REQUESTED** [review]
b96b4d0a59a3e5cff04a116961c629bc684c4f6e doesn't actually contain a `requirements.yml` file?

**Review by rco-ableton — APPROVED** [review]
LGTM 👍

**Comment by nre-ableton** [comment]
@ablbot autosquash

**Pull request merged**
